version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: ${APP_NAME}:latest
    container_name: ${APP_NAME}
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:8000"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
